{{- if and .Values.apiWriter.enabled .Values.apiWriter.persistence.data.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-data
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: stacks-blockchain-api
    hiro.so/stacks-blockchain-api-role: writer
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.apiWriter.persistence.data.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.apiWriter.persistence.data.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.apiWriter.persistence.data.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.apiWriter.persistence.data.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.apiWriter.persistence.data.size | quote }}
  {{- if .Values.apiWriter.persistence.data.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.apiWriter.persistence.data.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.apiWriter.persistence.data.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.apiWriter.persistence.data.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.apiWriter.persistence.data "global" .Values.global) | nindent 2 }}
{{- end -}}
