annotations:
  category: Blockchain
apiVersion: v2
appVersion: 2.4.0.0.4
dependencies:
  - condition: bitcoin-core.enabled
    name: bitcoin-core
    repository: https://charts.hiro.so/hirosystems
    tags:
      - hirosystems-bitcoin-core
    version: 2.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Stacks Blockchain Node
engine: gotpl
home: https://github.com/stacks-network/stacks-blockchain
icon: https://gaia.blockstack.org/hub/1ESMWxxhSRU64PXDQ7amaYeMcKqN7QsL37/nexus-circle-light-theme.png
keywords:
  - stacks
  - stx
  - blockchain
  - hiro
  - bitcoin
  - bitcoind
  - btc
maintainers:
  - name: Hiro Systems
    url: https://github.com/hirosystems/charts
name: stacks-blockchain
sources:
  - https://github.com/stacks-network/stacks-blockchain
  - https://docs.stacks.co/
version: 2.0.4
