# Deploy read-only stacks API if Values.apiRosettaReader.enabled == true
{{- if .Values.apiRosettaReader.enabled }}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}-rosetta-ro
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: stacks-blockchain-api
    hiro.so/stacks-blockchain-api-role: rosetta-ro
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.apiRosettaReader.autoscaling.enabled }}
  replicas: {{ .Values.apiRosettaReader.replicaCount }}
  {{- end }}
  {{- if .Values.apiRosettaReader.updateStrategy }}
  strategy: {{- toYaml .Values.apiRosettaReader.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: stacks-blockchain-api
      hiro.so/stacks-blockchain-api-role: rosetta-ro
  template:
    metadata:
      {{- if .Values.apiRosettaReader.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: stacks-blockchain-api
        hiro.so/stacks-blockchain-api-role: rosetta-ro
        {{- if .Values.apiRosettaReader.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "stacksBlockchainApi.serviceAccountName" . }}
      {{- include "stacksBlockchainApi.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.apiRosettaReader.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.apiRosettaReader.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.apiRosettaReader.podAffinityPreset "component" "stacks-blockchain-api" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.apiRosettaReader.podAntiAffinityPreset "component" "stacks-blockchain-api" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.apiRosettaReader.nodeAffinityPreset.type "key" .Values.apiRosettaReader.nodeAffinityPreset.key "values" .Values.apiRosettaReader.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.apiRosettaReader.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.priorityClassName }}
      priorityClassName: {{ .Values.apiRosettaReader.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.apiRosettaReader.schedulerName }}
      schedulerName: {{ .Values.apiRosettaReader.schedulerName | quote }}
      {{- end }}
      {{- if .Values.apiRosettaReader.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.apiRosettaReader.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.apiRosettaReader.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.apiRosettaReader.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if .Values.apiRosettaReader.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: stacks-blockchain-api
          image: {{ template "stacksBlockchainApi.image" . }}
          imagePullPolicy: {{ .Values.apiRosettaReader.image.pullPolicy }}
          {{- if .Values.apiRosettaReader.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.apiRosettaReader.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.apiRosettaReader.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.apiRosettaReader.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: STACKS_READ_ONLY_MODE
              value: "true"
            - name: STACKS_API_LOG_LEVEL
              value: {{ ternary "debug" "info" (or .Values.apiRosettaReader.image.debug .Values.diagnosticMode.enabled) | quote }}
            - name: STACKS_CHAIN_ID
              {{- if eq .Values.blockchainNetwork "mainnet" }}
              value: "0x00000001"
              {{- else if eq .Values.blockchainNetwork "testnet" }}
              value: "0x80000000"
              {{- else }}
              value: {{ default "0x80000000" .Values.blockchainNetwork | quote }}
              {{- end }}
            - name: STACKS_CORE_EVENT_PORT
              value: {{ default "3700" .Values.apiRosettaReader.containerPorts.socket | quote }}
            - name: STACKS_CORE_EVENT_HOST
              value: {{  default "0.0.0.0" .Values.apiRosettaReader.config.bindAddress | quote }}
            - name: STACKS_BLOCKCHAIN_API_PORT
              value: {{ default "3999" .Values.apiRosettaReader.containerPorts.api | quote }}
            - name: STACKS_BLOCKCHAIN_API_HOST
              value: {{ default "0.0.0.0" .Values.apiRosettaReader.config.bindAddress | quote }}
            - name: STACKS_PROFILER_PORT
              value: {{ default "9119" .Values.apiRosettaReader.containerPorts.profiler | quote }}
            - name: STACKS_CORE_RPC_HOST
              value: {{ include "stacksBlockchain.service.name" (index .Subcharts "stacks-blockchain") }}
            - name: STACKS_CORE_RPC_PORT
              value: {{ include "stacksBlockchain.service.ports.rpc" (index .Subcharts "stacks-blockchain") | quote }}
            - name: STACKS_API_ENABLE_FT_METADATA
              value: {{ ternary "1" "0" .Values.apiRosettaReader.config.enableFtMetadata | quote }}
            - name: STACKS_API_ENABLE_NFT_METADATA
              value: {{ ternary "1" "0" .Values.apiRosettaReader.config.enableNftMetadata | quote }}
            - name: STACKS_ADDRESS_CACHE_SIZE
              value: {{ default "50000" .Values.apiRosettaReader.config.stacksAddressCacheSize | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: PG_DATABASE
              value: {{ include "postgresql.v1.database" .Subcharts.postgresql }}
            - name: PG_SCHEMA
              value: {{ include "postgresql.v1.database" .Subcharts.postgresql }}
            - name: PG_PRIMARY_HOST
              value: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
            - name: PG_HOST
              value: {{ include "common.names.fullname" .Subcharts.postgresql }}-all
            - name: PG_PORT
              value: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
            - name: PG_USER
              value: {{ include "stacksBlockchainApi.postgresql.username" . }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ include "postgresql.v1.adminPasswordKey" .Subcharts.postgresql }}
                  name: {{ include "postgresql.v1.secretName" .Subcharts.postgresql }}
            - name: PG_APPLICATION_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- end }}
            - name: PG_CONNECTION_POOL_MAX
              value: {{ default "50" .Values.apiRosettaReader.config.pgConnectionPoolMax | quote }}
            - name: PG_STATEMENT_TIMEOUT
              value: {{ default "0" .Values.apiReader.config.pgStatementTimeout | quote }}
            {{- if .Values.cdn.enabled }}
            - name: IMGIX_TOKEN
              valueFrom:
                secretKeyRef:
                  key: {{ default "token" .Values.cdn.tokenSecretKey }}
                  name: {{ include "stacksBlockchainApi.cdn.secretName" . }}
            - name: IMGIX_DOMAIN
              value: {{ .Values.cdn.domain }}
            - name: STACKS_API_IMAGE_CACHE_PROCESSOR
              value: {{ .Values.cdn.imageCacheProcessorScript }}
            {{- end }}
            - name: NODE_ENV
              value: production
            {{- if .Values.apiRosettaReader.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.apiRosettaReader.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.apiRosettaReader.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.apiRosettaReader.resources }}
          resources: {{- toYaml .Values.apiRosettaReader.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http-api
              containerPort: {{ .Values.apiRosettaReader.containerPorts.api }}
            - name: tcp-socket
              containerPort: {{ .Values.apiRosettaReader.containerPorts.socket }}
            - name: tcp-profiler
              containerPort: {{ .Values.apiRosettaReader.containerPorts.profiler }}
              {{- if .Values.metrics.enabled }}
            - name: tcp-metrics
              containerPort: {{ .Values.apiRosettaReader.containerPorts.metrics }}
              {{- end }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.apiRosettaReader.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.apiRosettaReader.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http-api
          {{- else if .Values.apiRosettaReader.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.apiRosettaReader.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.apiRosettaReader.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http-api
          {{- else if .Values.apiRosettaReader.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.apiRosettaReader.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.apiRosettaReader.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http-api
          {{- else if .Values.apiRosettaReader.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.apiRosettaReader.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.apiRosettaReader.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.apiRosettaReader.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.apiRosettaReader.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.apiRosettaReader.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.apiRosettaReader.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
