name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Release Helm Charts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Hiro DevOps"
          git config user.email "45208873+blockstack-devops@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add Helm dependency repos
        run: |
          helm repo add hirosystems https://charts.hiro.so/hirosystems
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Release Hiro Systems charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: hirosystems
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
